package:
  name: cosign
  version: 2.2.4
  epoch: 2
  description: Container Signing
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 7c7e21c9cd48a1e4addb2d9c07f93a44d87de388
      repository: https://github.com/sigstore/cosign
      tag: v${{package.version}}

  - uses: go/bump
    with:
      deps: github.com/go-jose/go-jose/v3@v3.0.3 gopkg.in/go-jose/go-jose.v2@v2.6.3 google.golang.org/protobuf@v1.33.0 github.com/docker/docker@v24.0.9 golang.org/x/net@v0.23.0

  - uses: go/build
    with:
      ldflags: -s -w -X sigs.k8s.io/release-utils/version.gitVersion=${{package.version}}
      output: cosign
      packages: ./cmd/cosign

  - uses: strip

update:
  enabled: true
  github:
    identifier: sigstore/cosign
    strip-prefix: v
