#nolint:git-checkout-must-use-github-updates
package:
  name: jenkins-remoting
  version: 3206.vb_15dcf73f6a_9
  epoch: 1
  description: Jenkins Remoting is a library, and executable Java archive, which implements the communication layer in Jenkins
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - bash
      - openjdk-17-default-jvm

environment:
  contents:
    packages:
      - bash
      - busybox
      - ca-certificates-bundle
      - coreutils
      - maven
      - openjdk-17
      - openjdk-17-default-jvm
  environment:
    LANG: en_US.UTF-8
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/jenkinsci/remoting
      tag: ${{package.version}}
      expected-commit: b15dcf73f6a9b71da045bc471697702d99e871af

  - runs: |
      mkdir -p "${{targets.destdir}}/usr/share/jenkins"

      mvn -B -V -e --ntp -Dchangelist=${{package.version}} -Pquick-build clean package
      remoting_jar_filename="remoting-${{package.version}}.jar"
      cp target/$remoting_jar_filename "${{targets.destdir}}"/usr/share/jenkins/

      chmod +x "${{targets.destdir}}"/usr/share/jenkins/$remoting_jar_filename
      ln -sf "/usr/share/jenkins/$remoting_jar_filename" "${{targets.destdir}}/usr/share/jenkins/agent.jar"
      ln -sf "/usr/share/jenkins/$remoting_jar_filename" "${{targets.destdir}}/usr/share/jenkins/slave.jar"

update:
  enabled: true
  release-monitor:
    identifier: 1444
