package:
  name: mimalloc2
  version: 2.1.4
  epoch: 1
  description: "A compact general purpose allocator with excellent performance"
  copyright:
    - license: GPL-3.0-or-later

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - samurai
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/microsoft/mimalloc
      tag: v${{package.version}}
      expected-commit: e2141bc77e14b9bcad7631e9b6d392a3ee7eba99

  - name: 'Configure mimalloc'
    runs: |
      CFLAGS="$CFLAGS -D__USE_ISOC11" cmake -B build -G Ninja \
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_CXX_COMPILER=g++ \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_VERBOSE_MAKEFILE=ON \
        -DMI_INSTALL_TOPLEVEL=ON \
        -DMI_SECURE=ON

  - runs: |
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

subpackages:
  - name: "mimalloc2-dev"
    description: "headers for mimalloc2"
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - mimalloc2

update:
  enabled: true
  github:
    identifier: microsoft/mimalloc
    strip-prefix: v
    use-tag: true
    tag-filter: v2.
