package:
  name: mold
  version: 2.30.0
  epoch: 1
  description: "mold linker"
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - libtbb-dev
      - mimalloc2-dev
      - openssl-dev
      - samurai
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/rui314/mold
      tag: v${{package.version}}
      expected-commit: c7f6a91da512ef8a2634a1bef5d4ba82104659fe

  - name: 'Configure mold'
    runs: |
      cmake -B build -G Ninja \
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_CXX_COMPILER=g++ \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCMAKE_BUILD_TYPE=Release \
        -DMOLD_LTO=ON \
        -DMOLD_USE_SYSTEM_MIMALLOC=ON \
        -DMOLD_USE_SYSTEM_TBB=ON \
        -DBUILD_TESTING="OFF"

  - runs: |
      cmake --build build

  - runs: |
      DESTDIR="${{targets.destdir}}" cmake --install build

  - name: 'Clean up documentation'
    runs: |
      rm -rf ${{targets.destdir}}/usr/share/info

  - uses: strip

update:
  enabled: true
  github:
    identifier: rui314/mold
    strip-prefix: v
