package:
  name: py3-s3transfer
  version: 0.10.1
  epoch: 1
  description: "Amazon S3 Transfer Manager for Python"
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - py3-botocore
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/boto/s3transfer
      tag: ${{package.version}}
      expected-commit: b5d66a6fd76fbd170a7c4a87d45a962ed95df3f2

  - runs: |
      python3 setup.py build

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build

  - uses: strip

update:
  enabled: true
  github:
    identifier: boto/s3transfer
    use-tag: true
