package:
  name: py3-sphinx
  version: 7.3.7
  epoch: 1
  description: "Python Documentation Generator"
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - python3

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-flit-core
      - py3-gpep517
      - py3-installer
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/sphinx-doc/sphinx
      tag: v${{package.version}}
      expected-commit: 143474397a1a720cae23a8757894b440f6cef3c7

  - runs: |
      mkdir -p dist
      backend="$(python3 -m gpep517 get-backend)"
      python3 -m gpep517 build-wheel --wheel-dir dist --backend "$backend" --output-fd 1

  - runs: |
      python3 -m installer -d "${{targets.destdir}}" dist/sphinx-*.whl

  - uses: strip

update:
  enabled: true
  github:
    identifier: sphinx-doc/sphinx
    strip-prefix: v
