package:
  name: regclient
  version: 0.6.0
  epoch: 2
  description: Docker and OCI Registry Client in Go and tooling using those libraries
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - ca-certificates-bundle

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - go

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/regclient/regclient
      tag: v${{package.version}}
      expected-commit: a926bd5369c5b97f55dab6ca8e555e4b96284873

  - runs: |
      CGO_ENABLED=0 go build \
        -trimpath -ldflags "-s -w -extldflags -static -buildid=" \
        -o "${{targets.destdir}}/usr/bin/regctl" ./cmd/regctl

  - uses: strip

update:
  enabled: true
  github:
    identifier: regclient/regclient
    strip-prefix: v
