package:
  name: ruby3.2-console
  version: 1.24.0
  epoch: 1
  description: Beautiful logging for Ruby.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-fiber-local

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: console

pipeline:
  - uses: git-checkout
    with:
      expected-commit: fcbe0e5778f4c06275dfbd3cc7a5c9f3e152c4ad
      repository: https://github.com/socketry/console
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/console
    strip-prefix: v
    use-tag: true
