package:
  name: ruby3.2-async
  version: 2.10.2
  epoch: 1
  description: A concurrency framework for Ruby.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2
      - ruby3.2-console
      - ruby3.2-io-event
      - ruby3.2-timers

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: async

pipeline:
  - uses: git-checkout
    with:
      expected-commit: fd7b636dc1c31ce6f507471dbaca1384791dc71c
      repository: https://github.com/socketry/async
      tag: v${{package.version}}

  - uses: patch
    with:
      patches: 001-remove-signing-key.patch

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/async
    strip-prefix: v
