package:
  name: ruby3.2-connection_pool
  version: 2.4.1
  epoch: 3
  description: Generic connection pool for Ruby
  copyright:
    - license: MIT

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 8e3743b2021f51bcb3a6ec27de7cec836fcf9e72
      repository: https://github.com/mperham/connection_pool
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: connection_pool

update:
  enabled: true
  github:
    identifier: mperham/connection_pool
    strip-prefix: v
    use-tag: true
