package:
  name: ruby3.2-date
  version: 3.3.4
  epoch: 2
  description: A subclass of Object includes Comparable module for handling dates.
  copyright:
    - license: Ruby
    - license: BSD-2-Clause

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 77c38e1fd110afc0c51a1b5e2edfdb3701804c76
      repository: https://github.com/ruby/date
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: date

update:
  enabled: true
  github:
    identifier: ruby/date
    strip-prefix: v
