package:
  name: ruby3.2-fiber-local
  version: 1.0.0
  epoch: 4
  description: Provides a class-level mixin to make fiber local state easy.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby-3.2

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

vars:
  gem: fiber-local

pipeline:
  - uses: git-checkout
    with:
      expected-commit: cced2ed7b0ba9d7b32e64581ef29504d73fb4375
      repository: https://github.com/socketry/fiber-local
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

update:
  enabled: true
  github:
    identifier: socketry/fiber-local
    strip-prefix: v
    use-tag: true
