package:
  name: ruby3.2-net-protocol
  version: 0.2.2
  epoch: 2
  description: The abstract interface for net-* client.
  copyright:
    - license: Ruby
    - license: BSD-2-Clause
  dependencies:
    runtime:
      - ruby3.2-timeout

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: 258fdc626fd5027608e6992e61eb53a9b482b622
      repository: https://github.com/ruby/net-protocol
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: net-protocol

update:
  enabled: true
  github:
    identifier: ruby/net-protocol
    strip-prefix: v
