package:
  name: ruby3.2-faraday-follow_redirects
  version: 0.3.0
  epoch: 3
  description: |
    Faraday 2.x compatible extraction of FaradayMiddleware::FollowRedirects.
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ruby3.2-faraday

environment:
  contents:
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - git
      - ruby-3.2
      - ruby-3.2-dev

pipeline:
  - uses: git-checkout
    with:
      expected-commit: b2804e5930ecae7ec5b0cf23da5a3514e1f8d8ae
      repository: https://github.com/tisba/faraday-follow-redirects
      tag: v${{package.version}}

  - uses: ruby/build
    with:
      gem: ${{vars.gem}}

  - uses: ruby/install
    with:
      gem: ${{vars.gem}}
      version: ${{package.version}}

  - uses: ruby/clean

vars:
  gem: faraday-follow_redirects

update:
  enabled: true
  github:
    identifier: tisba/faraday-follow-redirects
    strip-prefix: v
    use-tag: true
