# Fetches the sonar-scanner-cli entrypoint script used in the upstream docker image. We
# need this for our image, but as it's stored in a different repo vs the source
# code, we need to fetch it and be able to auto-update.
package:
  name: sonar-scanner-cli-entrypoint
  version: 10.0.3.1430_5.0.1
  epoch: 0
  description: Fetches the sonar-scanner-cli entrypoint script from upstream docker repository.
  copyright:
    - license: LGPL-3.0-or-later

environment:
  contents:
    packages:
      - busybox

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/SonarSource/sonar-scanner-cli-docker
      expected-commit: 8ee21641b014850a1c50d0635aa337bf9a6ba369
      tag: ${{package.version}}

  - runs: |
      mkdir -p ${{targets.destdir}}/usr/bin/
      install -m755 bin/entrypoint.sh ${{targets.destdir}}/usr/bin/

update:
  manual: true
  github:
    identifier: SonarSource/sonar-scanner-cli-docker
