package:
  name: spark
  version: 3.5.0
  epoch: 0
  description:
  copyright:
    - license: Apache-2.0
  dependencies:
    runtime:
      - openjdk-17-jre
      - bash

environment:
  contents:
    packages:
      - busybox
      - ca-certificates-bundle
      - curl
      - maven
      - openjdk-17
      - openjdk-17-default-jvm
      - bash
      - wolfi-base
      - wolfi-baselayout

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/apache/spark
      tag: v${{package.version}}
      expected-commit: ce5ddad990373636e94071e7cef2f31021add07b

  - runs: |
      export LANG=en_US.UTF-8
      export JAVA_HOME=/usr/lib/jvm/java-17-openjdk

      ./build/mvn -DskipTests clean install
      mkdir -p ${{targets.destdir}}/usr/share/java/spark
      mv /root/.m2/repository/org/apache/spark/* ${{targets.destdir}}/usr/share/java/spark

update:
  enabled: true
  github:
    identifier: apache/spark
    use-tag: true
